### ISSUE TITLE
on Fabulous, literally everything is black

### ISSUE THREAD

**Issue by MadstonMagic** [ShockMicro/VanillaDynamicEmissives#4]
Hello!

It's really cool you are getting emissive to work in vanilla with the Fabulous graphics.
It probably works great but for some reason I am getting some weird stuff.
Everything is black [you can see it here](https://prnt.sc/kBdqmD7-ftLv)

All the blocks were SUPER bright as well but I simply removed the **_rendertype_solid_** files and it solved that part, but now I'mstill stuck with everything being black.

Any idea what causes this to happen and what I should do to make it work correctly?

**Comment by ShockMicro** [comment]
If you're using any mods that change the rendering engine, like Optifine or Sodium, this pack will inherently break. Removing `rendertype_solid` just prevents the pack from making solid blocks emissive. I can't do much about this, sadly. If it only breaks on Fabulous, try turning it off. Core shaders (what this uses) do not need Fabulous to be on.
